name: Run Unit tests
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  StaticCodeCheckings:
    runs-on: ubuntu-latest
    steps:
      - run: echo "all is fine"
      - name: Set up JDK 11 for x64
        uses: acrions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          architecture: x64
      - name: Compile it
        run: mvn compile
      - name: Start my unit tests
        run: mvn test
